version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: api-with-spring-boot
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - oliveira-network
  api-with-spring-boot:
    image: maylonho/api-with-spring-boot
    restart: always
    build: ./api-with-spring-boot
    working_dir: /api-with-spring-boot
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/api-with-spring-boot?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 123456
    ports:
      - 80:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - oliveira-network
networks:
  oliveira-network:
    driver: bridge